services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./logs/pg_log:/var/log/postgresql
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - finance_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    env_file: .env
    environment:
      DB_HOST: db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/__pycache__
    networks:
      - finance_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file: .env
    depends_on:
      - server
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  fiannce_data:
    name: finance_data
    external: false
