services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - finance_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./logs/pg_log:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./mcontr_dev
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./mcontr_dev:/app
    ports:
      - "5173:5173"
    environment:
      - API_URL=${API_URL}
      - SERVER_PORT=${SERVER_PORT}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - app
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  fiannce_data:
    name: finance_data
    external: false
